project:
  type: website
  output-dir: docs
website:
  page-footer: 
    left: "Copyright 2025, Tuomas Eerola" 
    right: 
      - icon: github
        href: https://github.com/tuomaseerola/
      - icon: twitter 
        href: https://twitter.com/tuomas_ee 
  title: "Gender in MusicPsych"
  navbar:
    left:
      - href: index.qmd
  page-navigation: true
  back-to-top-navigation: true
format:
  html:
    theme: yeti # lumen, pulse, materia, yeti, zephyr
    css: styles.css
    toc: false
    page-layout: full
