---
title             : "Gender Distribution of Authors in Music Psychology"
shorttitle        : "Gender in Music Psychology"
author: 
  - name          : "Tuomas Eerola"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Palace Green, Department of Music, Durham University, DH1 3RL Durham, United Kingdom"
    email         : "tuomas.eerola@durham.ac.uk"
  - name          : "Anna Czepiel"
    affiliation   : "2"
    address       : "Department of Psychology, University of Toronto, Mississauga, Canada"
    email         : "a.czepiel@utoronto.ca"
affiliation:
  - id            : "1"
    institution   : "Department of Music, Durham University"
  - id            : "2"
    institution   : "Department of Psychology, University of Toronto"

author_note: |
  Tuomas Eerola is at the Department of Music, Durham University, UK.
  Anna Czepiel is at the Department of Psychology, University of Toronto, Canada.

abstract: |
 blah blah blah.  
keywords          : "gender, transparency, music psychology, open science, meta-research"
wordcount         : "5555"
figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no
csl: apa7.csl
class             : "man"
bibliography: references.bib
format:
  html: default
---

```{r global options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

# Introduction


Equality – Why Should We Care?

- Lack of equity impacts: 

- productivity
- innovation
- job satisfaction

Academia has acknowledged serious challenges in gender equity

- women less present in positions of power (e.g. 30% UK profs)
- pay gap is wider in academia (16%) than in other sectors (9%)
- women represent fewer than 30% authorships globally

Weave these studies into the narrative: 

- @son2022scientific Scientific authorship by gender

- @shah2021gender showed how far off is the gender parity in scientific authorship using a bibliometric analysis

- @rock2021quantifying quantified the gender gap in authorship in herpetology, showing that ....

- @ni2021gendered presented an overview of the gendered nature of authorship

See @gonzalez2020women for a baseline from other disciplines:

- Hard Sciences (N=119,592) = 0.148
- Bio and Social Sciences (N=262,122) =  0.433
- Psychology (N=90,067) =  0.452

What is the situation in music psychology?

## Aims

Our aim is to find out what is the gender distribution in the specialist journals of music psychology. What is the proportion of first authors in the published papers in the last 10 years? What is the situation with all authors and senior authors? Are there specific trends in terms of countries of the affiliations, topics, or time?

# Methods

## Materials and analyses

- Dataset description. All papers between 2010 and 2022 from specialist journals used in [@jakubowski2024].

- Initial attribution of genders based on first names. Automatic attribution of gender based on first name databases (Gender API) + manual fixes

- Quality control.

- Manual corrections.

- Expansion into all other first names (requires getting more data and repeating the process above).

# Results

- Overall proportion: First authors

- First authors prevalence by Country (Figure)

- Association with the topics (Figure?)

- Time trends (Figure)

# Conclusions

- Encouraging overall?

- Compare with sub-disciplines of psychology [@gonzalez2020women] Psychology: First authors (N=33,631)

- Female role models (past and present) exist in music psychology (list names and their eminent roles, chairs of societies, editors of the main journals, etc. Diana Deutsch, Carol Krumhansl, Irene Deliege, to a more recent ICMPC and ESCOM presidents).

- Is this an area that appeals to women? (see comparison to sub-disciplines of psychology, where "softer" areas tend to have higher proportion)

- Not matched by musicology: 25% female profs, 38% below??? (these are just some UK stats, I don't think the field-wide analysis has been done)


### Funding statement

???

### Competing interests statement

There were no competing interests.

### Open practices statement

Study data, analysis scripts and supporting information is available at GitHub, <https://tuomaseerola.github.io/gender_in_music_psych>.

# References
